blog/urls.py
from django.urls import path
from .views import BlogPostView, BlogPostDetailsView

app_name = 'blog'

urlpatterns = [
    path('', BlogPostView.as_view(), name = 'all_blogs'),
    path('<int:blog_id>.html', BlogPostDetailsView.as_view(), name = 'read-more'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('blog/', include('blog.urls'))
    # path('', views.Home.as_view(), name = 'home')
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Post(models.Model):
    title       = models.CharField(max_length=155)
    description = models.TextField()
    created_at  = models.DateField()

    def __str__(self):
        return '#' + str(self.id) + ' - ' + self.title + '   @' + str(self.created_at)

portfolio/models.py
from django.db import models
#from django.db.models import Model

class Project(models.Model):
    title       = models.CharField(max_length = 100)
    description = models.CharField(max_length = 250)
    image       = models.ImageField(upload_to = 'portfolio/images/')
    url         = models.URLField(blank=True)
    #description = models.TextField()

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views import View
from .models import Post

class BlogPostView(View):
    def get(self, request):

        items_per_page = 3

        page = int(request.GET.get('page', 1))

        # equals to DESC
        posts = Post.objects.order_by('-created_at')

        paginator = Paginator(posts, items_per_page)
        page      = paginator.get_page(page)
        # posts = []

        return render(
            request,
            'blog/all_blogs.html',
            {'page': page}
        )


class BlogPostDetailsView(View):
    def get(self, request, blog_id):

        post = get_object_or_404(Post, pk=blog_id)

        return render(
            request,
            'blog/detail.html',
            {'post': post}
        )

portfolio/views.py
from django.shortcuts import render
from .models import Project

# class Home:
    # def as_view():
        # return HttpResponse('yesss')

def home(request):

    projects = Project.objects.all()

    return render(
        request,
        'portfolio/home.html',
        {'projects': projects}
    )

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}
    <div class="container text-center">

      <h1>Blogs.</h1>
      <h5>{{page.paginator.num_pages}} page{{ page.paginator.num_pages | pluralize}}</h5><!-- gives `pages` -->

      {% for p in page %}
      <div class="card m-2" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ p.title }}</h5>
          <p class="card-text">{{ p.created_at | date:'d M Y' | upper }}</p>

          <a href="{% url 'blog:read-more' p.id %}" class="btn btn-primary">Read more</a>

        </div>
       </div>

        {% empty %}

        <div>No articles yet.</div>

        {% endfor %}


        <div class="pagination">
          <span class="step-links">
              {% if page.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ page.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                  Page {{ page.number }} of {{ page.paginator.num_pages }}.
              </span>

              {% if page.has_next %}
                  <a href="?page={{ page.next_page_number }}">next</a>
                  <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
          </span>
        </div>
      </div>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}
    <div class="container text-center">

      <h1>Blogs</h1>

          <h4>#{{ post.id }} - {{ post.title }}</h4>
          <div class="date">{{ post.created_at | date}}</div>

          <!-- <b>Short:</b> -->
          <!-- <p>{{ post.description }}</p> -->

          <b>Full:</b>
          <p class="lead">{{ post.description|safe|truncatechars:500 }}</p>

          <!-- <b>Full:</b> -->
          <!-- <p>{{ post.description|striptags }}</p> -->

      </div>

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>Django test project by IgorErmakov</title>

    <style>
      .projects {
        display: flex;
      }

    </style>

  </head>
  <body>

    <div class="alert alert-success" role="alert">
      Portfolio & blog
    </div>
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'blog:all_blogs' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:all_blogs' %}">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>

      <!-- <img src="{% static 'portfolio/dino.jpg' %}" width="150" alt="dino"/> -->


    {% block content %}{% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}

     <h2 class="m-3">Proejcts list</h2>

     <div class="projects">
      {% for p in projects %}
      <div class="card m-2" style="width: 18rem;">
        <img src="{{ p.image.url }}" width="100" class="card-img-top" />
        <div class="card-body">
          <h5 class="card-title">{{ p.title }}</h5>
          <p class="card-text">{{ p.description }}</p>
          {% if p.url %}
          <a href="{{ p.url }}" class="btn btn-primary">Open website</a>
          {% endif %}
        </div>
       </div>
       {% endfor %}
     </div>


{% endblock %}